(ns kigen.sgp
  (:require [clojure.math.combinatorics :as combinatorics]
            [kigen.orbit :refer [full-orbit-bulk right-actions set-action]]
            [kigen.pbr :as pbr]))

(declare sgp-by-gens
         commutative?)

(defn sgp-by-gens
  "Computes all elements of a semigroup generated by gens combined by the
  given binary operation mul. Partitioned binary relation composition is the
  default operation."
  ([gens] (sgp-by-gens gens pbr/mul))
  ([gens mul]
   (full-orbit-bulk gens (set-action (right-actions mul gens)))))

(defn commutative?
  "Brute-force checking of commutativity of a semigroup."
  [sgp]
  (every? #(= (pbr/mul (first %) (second %)) (pbr/mul (second %) (first %)))
          (combinatorics/combinations sgp 2)))
