(ns kigen.sgp
  "General functions for semigroups. Black box style, the elements
  and the operation need to be supplied."
  (:require [clojure.math.combinatorics :as combinatorics]
            [kigen.orbit :refer [full-orbit-bulk right-actions set-action]]))

(declare sgp-by-gens
         commutative?)

(defn sgp-by-gens
  "Computes all elements of a semigroup generated by gens combined by the
  given binary operation mul."
  [gens mul]
  (full-orbit-bulk gens (set-action (right-actions mul gens))))

(defn commutative?
  "Brute-force checking of commutativity of a semigroup."
  [sgp mul]
  (every? #(= (mul (first %) (second %)) (mul (second %) (first %)))
          (combinatorics/combinations sgp 2)))
